### ISSUE TITLE
Ledger Nano S support via OTG

### ISSUE THREAD

**Issue by rumatoest** [LedgerHQ/ledger-live-mobile#722]
Hello. 
Well I understand that primary goal for mobile app is Ledger Nano X.
But it looks that you can actually work with Ledger Nano S on phones with OTG support.

Are any future plans to integrate Nano S via OTG ?

**Comment by gre** [comment]
Yes it's possible.

Yes it's planned (not sure about the exact deadline we have in mind).

Technically the remaining work is:

- our current hid support implementation is not performant because it blocks the main thread. code is in https://github.com/LedgerHQ/ledgerjs/tree/master/packages/react-native-hid
- we need to do a redesign of our app to includes the possibility that you are not with a Nano X. It is pretty important because the way you validate on a Nano X and on a Nano S is pretty different, also wording will vary.

**Comment by compuguy** [comment]
SO @gre has this been implemented, since the issue had been closed?
