### ISSUE TITLE
[Question] Reinstalling the mobile app after resetting will restore all accounts.

### ISSUE THREAD

**Issue by Luuk2016** [LedgerHQ/ledger-live-mobile#757]
After i reset Ledger Live i see the "Get started" screen.
If i reinstall the app it will ask for my fingerprint.
When i unlock the app it will show all my accounts.
Why is this happening? 
I am asking this out of curiosity.

Thanks

#### Steps to reproduce the behavior
1. Reset Ledger live in the settings.
2. Reinstall Ledger Live.
3. Open the app

**Comment by juan-cortes** [comment]
Do you mean reinstalling the app as in uninstalling and then installing from the PlayStore/AppStore?
Which platform are you using? 
Which version of the app are you running?

I've tested with the current production version on Android and the latest develop version and I can't replicate your findings.

**Comment by gre** [comment]
The only reason I see this could happen is that the Reset action didn't had enough time to effectively "save" the new state in the app state (this happen after some delay: https://github.com/LedgerHQ/ledger-live-mobile/blob/develop/src/index.js#L63 )
This would also be on Android only because Android keeps the data of apps even after deletion, not iOS.

**Comment by gre** [comment]
fixed in upcoming 1.2.0
