### ISSUE TITLE
Receive Push Notifications for Significant Price changes

### ISSUE THREAD

**Issue by drewdickenson** [LedgerHQ/ledger-live-mobile#761]
Feature Request:

Fixed or preferably user manageable alerts from the mobile app for significant price changes in assets in that user’s portfolio. 

Delta does this now and it is a very useful feature, even more so if you let the users set the thresholds for these alerts.

**Comment by gre** [comment]
Thanks for your feature request.

I don't think we are likely to implement this feature right now because our app is not much a price tracker. I would recommend the use of such apps like Delta / any bitcoin tracker for this use-case for the time being.

Push notifications as also requested for when receiving assets ( #730 ) but it's also a tricky topic especially for privacy reason.
